### ISSUE TITLE
Reordering within project and/or folder

### ISSUE THREAD

**Issue by Brainyac** [heybourn/headwind#10]
Cheers,

currently it's only possible to reorder the classes within the opened file.

It would be also good to have an option to let it reorder the whole classes within a selected folder or even the whole project.

Especially necessary if we want to implement this not only from the scratch of a project.

Thanks,
~ Brain

**Comment by praveenperera** [comment]
Hey I think @heybourn if building this in to the plugin right now.

However you can use the CLI tool inspired by headwind to do that now: https://github.com/avencera/rustywind

**Comment by praveenperera** [comment]
I've added this functionality, I'm waiting to get some people to test it before I do a PR

You can test by manually install the plugin from: https://github.com/avencera/headwind/blob/run-on-project/headwind-1.5.5.vsix

**Comment by heybourn** [comment]
This is now possible with the latest version of Headwind  🥳
