### ISSUE TITLE
Support `class` tag while using a JS string

### ISSUE THREAD

**Issue by deadcoder0904** [heybourn/headwind#101]
**Is your feature request related to a problem? Please describe.**
I'm using Remark to style a table in Tailwind. I can't style it directly as my table is in markdown so I have to use Remark as an intermediary step to do it.

I have an array which contains `table` tag & I keep pushing `tr`, `th`, etc... onto it like:

```js
const str = []
str.push(`<table class="table-fixed max-w-7xl full-bleed md:mx-12 divide-y divide-gray-200">`)
str.push(`<thead class="">`)
str.push(`<tr class="">`)
str.push(`<th class="px-6 py-3 bg-gray-50 text-left text-2xl font-semibold text-blue-gray-700 tracking-wider">${k}</th>`)
```

**Describe the solution you'd like**
I'd love for Headwind to sort classes in JS files too where a string uses `class` tag.

**Comment by petertriho** [comment]
@deadcoder0904 this can be done by adding this to your settings.json

**Comment by deadcoder0904** [comment]
Good to know :)

**Comment by petertriho** [comment]
Fixed in https://github.com/heybourn/headwind/pull/109
