### ISSUE TITLE
Extract the core functionality and provide a CLI tool

### ISSUE THREAD

**Issue by shackra** [heybourn/headwind#105]
**Is your feature request related to a problem? Please describe.**
I'm an Emacs user and would like to use this tool at work, however seems no CLI option is available

**Describe the solution you'd like**
Extracting the core functionality into a separate package or somethin', then coupling that with the vscode extension for vscode users and offering a CLI that receives input from stdin and spits the results to stdout for everybody else

**Describe alternatives you've considered**
letting my coworkers sort the classes on their pull requests (not really an alternative)

**Additional context**
None.

**Comment by praveenperera** [comment]
Hey @shackra I made a CLI version of Headwind here: https://github.com/avencera/rustywind
