### ISSUE TITLE
Support Windi CSS compiler

### ISSUE THREAD

**Issue by ThaddeusJiang** [heybourn/headwind#115]
Hello !

There's another implementation of TailwindCSS called [windicss](https://github.com/windicss/windicss), that offer many advantages for some use cases like mine.

I wondered if it could be supported, thank you very much.

**Comment by Async0x42** [comment]
It seems like this would just require:

```
    "activationEvents": [
        "workspaceContains:**/tailwind.config.js",
        "onCommand:headwind.sortTailwindClasses",
        "onCommand:headwind.sortTailwindClassesOnWorkspace"
    ],
```

to include windi.config.js/ts

**Comment by praveenperera** [comment]
We aren't going to support WindiCSS. They removed all mentions to TailwindCSS from their repo.

Currently they use the same all the classes but that might change in the future. 

They can of course fork this and make it work for them.

**Comment by kansson** [comment]
This can be accomplished by using `windicss.sortOnSave` setting.
