### ISSUE TITLE
Update version on vs marketplace

### ISSUE THREAD

**Issue by iofjuupasli** [heybourn/headwind#121]
Last version on https://marketplace.visualstudio.com/items?itemName=heybourn.headwind is:
`Last updated | 1/15/2021, 11:05:40 PM`

So it's outdated version, for example, it doesn't have class names in config like `bottom-1`, that causes invalid sort order in my project.

**Comment by praveenperera** [comment]
That’s my bad, I’ve been meaning to get a new version out. Before I do that would you be willing to test it out to make sure there are no issues?

**Comment by petertriho** [comment]
@praveenperera will need to merge in https://github.com/heybourn/headwind/pull/114 first before a release is made. There is an issue with the current multistage regex capturing all strings

**Comment by praveenperera** [comment]
I've created a `.vsix` for version 2.0.0, please test it out and let me know if there's any problems. 

If there's no problems i will publish v2.0.0 on May 1st
