### ISSUE TITLE
Half margins and paddings broke auto sort

### ISSUE THREAD

**Issue by laurensiusadi** [heybourn/headwind#128]
Auto sort doesn't work for half margins and paddings: `m-0.5 p-1.5 mt-2.5 pb-3.5` etc. All margins class and padding with `.5`
If I remove the `.5` it works as intended.
I'm using 2.0.0, also happen on previous versions.

**Comment by praveenperera** [comment]
Can you try to use this custom regex for HTML:

```
"/\\bclass\\s*=\\s*[\\\"\\']([\\._a-zA-Z0-9\\s\\-\\:\\/]+)[\\\"\\']/"
```

**Comment by laurensiusadi** [comment]
Sorry, according to docs I need to put the regex on `package.json`, assuming that belongs to the extension, where can I find it?

**Comment by laurensiusadi** [comment]
Just had time to check this again, I found the place to put it, in Extension settings json file. On CSS file it works, not sure with HTML,  because event with .5 deleted somehow it doesn't work at all. I'm testing on Vue file.
