### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by darrist** [heybourn/headwind#132]
**Describe the bug**
Unable to sort using headwind, says exec problem.

- I have checked the file its trying to exec exists.
- I have tried multiple version from 1.6.3 to 1.7.0 latest

```
Headwind error: /home/darris/.vscode-insiders/extensions/heybourn.headwind-1.6.3/node_modules/rustywind/bin/rustywind: /home/darris/.vscode-insiders/extensions/heybourn.headwind-1.6.3/node_modules/rustywind/bin/rustywind: cannot execute binary file
```

**To Reproduce**
1. Install headwind
2. Sort with tailwind

**Expected behavior**
Should sort without problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/21124691/119460361-2c78cb00-bd71-11eb-8d3f-e0119c3bde09.png)

**Desktop (please complete the following information):**
 - OS: x86_64 Linux 5.12.5-arch1-1
 - Browser: Chromium 
 - Version 90.0.4430.212 Arch Linux
 - VSCode: 1.57.0-insider

**Additional context**

**Comment by f3bruary** [comment]
I have the same issue
```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-16T15:21:33.370Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.42-1-MANJARO
```

**Comment by f3bruary** [comment]
@darrist Are you using this in a NextJS project by any chance ? I noticed ctrl+alt+t works (to order classes on the current doc). But the command to order all classes in the entire workspace fails with that error.
