### ISSUE TITLE
Percent width and breakpoints not sorted

### ISSUE THREAD

**Issue by mohamedsabil83** [heybourn/headwind#17]
**My classes:**
`<div class="w-full flex p-2 lg:w-1/3 lg:flex-grow">`

**Expected but not happen:**
`<div class="flex w-full p-2 lg:flex-grow lg:w-1/3">`

**when remove `lg:` and replace `w-1/3` with `w-2` it woks:**
`<div class="flex flex-grow w-2 w-full p-2">`

**Comment by heybourn** [comment]
Headwind currently sorts any breakpoint classes (or unknown classes) to the end of the list. Is this the issue you're facing?

**Comment by mohamedsabil83** [comment]
No problem with unknown classes as it was sorted to the end as expected. but when breakpoint present, sort does not work at all.

**Comment by heybourn** [comment]
I'm about to push an update. Can you test in 5 minutes and let me know if the issue still occurs?

**Comment by heybourn** [comment]
Update should be available through VS Code now!

**Comment by heybourn** [comment]
I've tested with the new update and sorting seems to work as it should. I'm closing this issue and will open another for sorting breakpoints.

**Comment by mohamedsabil83** [comment]
Yes, It's working now with putting a breakpoint and unknown classes to the end.
Waiting for sorting breakpoints.
Thank you. Good job.
