### ISSUE TITLE
Is it possible to sort classes on `.astro` files?

### ISSUE THREAD

**Issue by AlexMayol** [heybourn/headwind#194]
**Is your feature request related to a problem? Please describe.**
I'm trying to get the VSCode extension working on `.astro` files (from [AstroJS](https://astro.build/))

**Describe the solution you'd like**
Is there a config that works for these files? I haven't figured it out.

**Additional context**
When saving a file, classes are not being sorted as they are in `.html` files. Example
`<header class="bg-primary-900 text-white md:p-4 p-2 sticky top-0 z-50">`

**Comment by phaberest** [comment]
Hi @AlexMayol 🙌🏻 I would suggest you to move to the prettier or eslint plugins as suggested in https://github.com/heybourn/headwind/issues/185#issuecomment-1220914816

**Comment by AlexMayol** [comment]
@phaberest Thank you, I didn't know about the plugin!
