### ISSUE TITLE
[Feature Request] PHPStorm / Jetbrains Port

### ISSUE THREAD

**Issue by tance77** [heybourn/headwind#2]
PHPStorm / Jetbrains Port

**EDIT**
Coming Soon.

**Comment by tance77** [comment]
Thanks @WalrusSoup for this port. WIP

https://plugins.jetbrains.com/plugin/13376-tailwind-formatter/

**Comment by heybourn** [comment]
Awesome! I'll close this issue now.

**Comment by hacknug** [comment]
Should we add a mention to this in `README.md`?

**Comment by heybourn** [comment]
Good idea. I was going to do this today but completely forgot - will add now.
