### ISSUE TITLE
Add support for React (JSX)

### ISSUE THREAD

**Issue by praveenperera** [heybourn/headwind#4]
**Is your feature request related to a problem? Please describe.**
This won't work inside JSX files

**Describe the solution you'd like**
We could edit the regex to include jsx `className=....`
https://github.com/heybourn/headwind/blob/master/src/extension.ts#L8

**Alternatives**
Check how vscode-tailwindcss works and use a similar approach of only running on certain file types? Maybe make it possible to work with other languages like Elm?

**Comment by heybourn** [comment]
This should be relatively easy to implement. Do you have any other examples of the _class_ tag varying between languages/frameworks?

**Comment by praveenperera** [comment]
The one that comes to mind is Elm:

https://package.elm-lang.org/packages/elm/html/latest/Html-Attributes#class

But I can make the change for it to work with JSX for now.

**Comment by Dobby89** [comment]
Would this fix work with .tsx files in typescript?

**Comment by heybourn** [comment]
If it's a simple regex change then it should work globally (so long as the extension can find a _class_ value of some kind)

**Comment by SaschaDens** [comment]
Would it be a possibility to have this available as a setting?
This way it remains flexible regardless of the syntax.

**Comment by heybourn** [comment]
Go for gold!
