### ISSUE TITLE
Classes with responsive prefixes not sorted correctly

### ISSUE THREAD

**Issue by ivosabev** [heybourn/headwind#56]
### Current
```html
<div class="xl:hidden sm:block lg:hidden md:hidden">Small</div>
```

### Expected
```html
<div class="sm:block md:hidden lg:hidden xl:hidden">Small</div>
```

**Comment by heybourn** [comment]
Please see #52. This is a known issue and the only fix right now is to manually add these responsive classes to your Headwind config.

**Comment by NoelDeMartin** [comment]
@heybourn I couldn't manage to get this working, can you share an example of the Headwind config you are using to fix this?

**Comment by amritk** [comment]
> @heybourn I couldn't manage to get this working, can you share an example of the Headwind config you are using to fix this?

Did you manage to figure it out?

**Comment by NoelDeMartin** [comment]
@amritk I didn't, actually I stopped using this altogether. I think eventually I'll use [the official Prettier plugin](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier), but I still have to sort some things out before starting (pun intended). So I'm not using anything to sort my classes at the moment.

**Comment by amritk** [comment]
oo thanks, I'm going to check that out
