### ISSUE TITLE
Support `classnames` package

### ISSUE THREAD

**Issue by alexluong** [heybourn/headwind#58]
**Is your feature request related to a problem? Please describe.**

When working with Tailwind and React, I usually reach out for [`classnames`](https://npmjs.com/package/classnames). It seems like there's is no way `headwind` can support it.

**Describe the solution you'd like**

A workaround is a command that will sort whatever is in "selection", so that I can highlight a big string and have it sorted.

**Comment by arturocr** [comment]
I think it's a thing of adding a new capturing group to the existing [regular expressions](https://github.com/heybourn/headwind/blob/master/package.json#L1819), sadly I'm not that good at writing RegEx. Hopefully, someone would be able to add one.
BTW, [`clsx`](https://www.npmjs.com/package/clsx) is a nicer alternative to `classnames`, so it would be awesome to include support for it as well. 🙂

**Comment by msreekm** [comment]
did anyone figure out how to sort classnames within "classname" pkg?
