### ISSUE TITLE
Trigger changes on save

### ISSUE THREAD

**Issue by alexander-rieder** [heybourn/headwind#6]
Hey :)

Thanks for the cool plugin. Could we get an option to trigger this plugin when we save a file?

Greetings,

Alex

**Comment by heybourn** [comment]
Hey Alex. This is something I'm currently looking into as I'd like it too. I'll close this issue when it's solved!

**Comment by sietzekeuning** [comment]
Would be an awesome addition!

**Comment by Tchoupinax** [comment]
It will be very nice to have !

**Comment by danimalweb** [comment]
Would be great to have!
