### ISSUE TITLE
Enable Support for Template Literal

### ISSUE THREAD

**Issue by kentcdodds** [heybourn/headwind#67]
**Describe the bug**

Headwind will not sort these:

```javascript
export function FormGroup({className = '', ...props}) {
  return <div className={`flex-col flex ${className}`} {...props} />
}
```

**To Reproduce**

Open a JSX file in a Tailwind-enabled project, copy/paste that code and hit save and notice it is not sorted.

**Expected behavior**

I expect it to be sorted.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by petertriho** [comment]
Fixed in https://github.com/heybourn/headwind/pull/109

**Comment by kentcdodds** [comment]
Thanks!

**Comment by boompikachu** [comment]
Is this fix? I still got the same problem with the newest version

**Comment by petertriho** [comment]
@boompikachu it has been fixed but the @ryanhhhh seems to be busy and has not been able to release it to the vscode marketplace yet.

If you want, you can have a look at manually installing the update https://github.com/ryanhhhh/headwind/issues/122

**Comment by boompikachu** [comment]
Thanks @petertriho
