### ISSUE TITLE
sort JSX with when using bracket

### ISSUE THREAD

**Issue by aeonthread** [heybourn/headwind#84]
case that work :
```jsx
className="flex justify-center items-center w-full border h-16 hover:border-pink-900 hover:text-pink-900"
```
case-1 that doesn't work :
```jsx
className={"flex justify-center items-center w-full border h-16 hover:border-pink-900 hover:text-pink-900"}
```
case-2 that doesn't work :
````jsx
className={"flex justify-center items-center w-full border h-16 hover:border-pink-900 hover:text-pink-900" + REACT_STATE}
````
is it there any custom REGEX to fix this ?
it's the best extension on VSCODE btw :+1:

**Comment by praveenperera** [comment]
@aeonthread  https://regex101.com/r/VaarqJ/1

**Comment by aeonthread** [comment]
thatnk you for reply so i added this to vscode config file but still doenst work
```json
   "headwind.classRegex": {
        "typescriptreact": "(?:\bclassName\\s*=\\s*{?[\"\\']([_a-zA-Z0-9\\s\\-\\:\/]+)[\"\\'])|(?:\btw\\s*([_a-zA-Z0-9\\s\\-\\:\/]*))"
    },
```

btw i scaped characters again because vscode was complaining about wrong scape so i changed your regex from :
`(?:\bclassName\s*=\s*{?[\"\']([_a-zA-Z0-9\s\-\:\/]+)[\"\'])|(?:\btw\s*([_a-zA-Z0-9\s\-\:\/]*))
`
to this :
`"(?:\bclassName\\s*=\\s*{?[\"\\']([_a-zA-Z0-9\\s\\-\\:\/]+)[\"\\'])|(?:\btw\\s*([_a-zA-Z0-9\\s\\-\\:\/]*))"`
but still doesnt't sort

**Comment by GavinRay97** [comment]
@aeonthread This should work from #85 :+1: 
```json
"headwind.classRegex": {
  "typescriptreact": "(?:\\b(?:class|className)?\\s*=\\s*{?[\\\"\\']([_a-zA-Z0-9\\s\\-\\:/]+)[\\\"\\']}?)"
}
```

**Comment by aeonthread** [comment]
> @aeonthread This should work from #85 
> (The only difference was a closing bracket I think, and on yours you just needed to double-escape the backslashes as well)
> 
> ```json
> "headwind.classRegex": {
>   "typescriptreact": "(?:\\b(?:class|className)?\\s*=\\s*{?[\\\"\\']([_a-zA-Z0-9\\s\\-\\:/]+)[\\\"\\']}?)"
> }
> ```

i just copy and paste your answer into the setting doesn't work, as soon as i remove curly brackets it get sort perfectly again so i think problem is still with these { } (curly brackets).

this doesnt work:
```jsx
<div className={"bg-white flex w-full max-h-screen relative flex-col"} />
```
this works:
```jsx
<div className="bg-white flex w-full max-h-screen relative flex-col" />
```

**Comment by heybourn** [comment]
Closing as this has been solved
