### ISSUE TITLE
cmd + shift + t hotkey overrides the default vscode hotkey

### ISSUE THREAD

**Issue by tzusman** [heybourn/headwind#98]
**Describe the bug**

When enabled, this extension overrides one of the default vscode hotkeys.  The default hotkey is used to re-open the previously closed tab.

**To Reproduce**
1. Install extension
2. Open two editor tabs
3. Close one of them
4. use hotkey cmd + shift+ t

**Expected behavior**

With the default vscode settings, the tab you just closed should reopen.

**Screenshots**

n/a

**Desktop (please complete the following information):**
 - OS: OSX
 - VS Code Version: 1.50.1

**Proposal**

Create a setting to disable this hotkey

**Comment by antenando** [comment]
This is a main VSCode hotkey. It should be mapped to something else, like alt+shift+t, whatever
